blog/urls.py
from django.urls import path
from .views import comment_api, like_btn, post_detail, post_list_view, post_view, add_post, update_post

urlpatterns = [
    path('', post_list_view, name = "blogs_list"),
    path('addPost', add_post, name = "add_post"),
    path('<int:id>', post_list_view, name = "blogs_category_list"),
    path('<int:id>', post_view, name = "post_detail"),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/', post_detail, name='post_detail'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/update', update_post, name='update_post'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/comment', comment_api, name = "comment"),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/<int:id>/like', like_btn, name='like'),
    # path('comment/<int:id>', comment_api, name = "comment"),
    # path('<int:id>', post_category_list, name='job_details'),
    # path('addJob', add_job, name='jobEditor'),
    # path('<int:id>/like', like_btn, name='like'),
    # # path('<int:id>/dislike', disLiker, name='dislike'),
]

app_name = 'blog'

home/urls.py
from django.urls import path
from .views import candidates_view, companies_view, home_view
urlpatterns = [
    path('', home_view, name = "index"),
    path('candidates', candidates_view, name = "candidates"),
    path('companies', companies_view, name = "companies"),
    
]    

app_name = 'home'

job/urls.py
from django.urls import path
from .views import category_jobs, job_apply, job_details, jobs, add_job, like_btn

urlpatterns = [
    path('', jobs, name = "job_list"),
    path('<int:id>', job_details, name='job_details'),
    path('addJob', add_job, name='jobEditor'),
    path('<int:id>/like', like_btn, name='like'),
    path('<int:id>/apply', job_apply, name='application'),
    path('<int:id>', category_jobs, name='category_jobs'),
]

app_name = 'job'

project/urls.py
from django.contrib import admin
from django.urls import path, include 
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls', namespace='register')),
    path('admin/', admin.site.urls),   
    path('jobs/', include('job.urls', namespace='jobs')),
    path('contact-us/', include('contact.urls', namespace='contact')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('', include('home.urls', namespace="home")),
    path('blogs/', include('blog.urls', namespace='blogs')),
    

]

if settings.DEBUG:
    #urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.contrib.auth.models import User
from django.db import models
from django.utils import timezone
from django.conf import settings
from django.urls import reverse
from taggit.managers import TaggableManager
from ckeditor.fields import RichTextField
from django.utils.text import slugify 

# Create your models here.
User = settings.AUTH_USER_MODEL

class PublishedManager(models.Manager):
    def get_queryset(self):
        return super(PublishedManager,self).get_queryset().filter(status='published')

def upload_post_image(instance, filename):
    extension = filename.split('.')[1]
    if instance.title:
        return '%s.%s'%(instance.title, extension)
    else:
        return 'posts/imags/%s.%s'%(instance.name, extension)




class Category(models.Model):
    title = models.CharField(max_length=50)

    def __str__(self):
      return self.title

class Post(models.Model):
    STATUS_CHOICES = (
        ('draft', 'Draft'),
        ('published', 'Published'),
    )
    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250, unique_for_date='publish')

    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='posts')
    image = models.ImageField(upload_to=upload_post_image)
    body = RichTextField(blank=True, null=True)
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='draft')
    objects = models.Manager() # The default manager.
    published = PublishedManager() # Our custom manager
    tags = TaggableManager()
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True, related_name='posts')
    likers = models.ManyToManyField(User, related_name='liked_posts', blank=True)


    class Meta:
        ordering = ('-publish',)

    def __str__(self):
       return self.title

    def get_absolute_url(self):
        return reverse('blogs:post_detail',
        args=[self.publish.year,
        self.publish.month,
        self.publish.day, self.slug])  
         
    def save(self, *args, **kwargs): 
        self.slug = slugify(self.title) 
        super(Post, self).save(*args, **kwargs) 

class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='post_comments')
    commenter = models.ForeignKey(User, related_name='blog_posts',on_delete=models.CASCADE) 
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
      ordering = ('created',)

    def __str__(self):
      return f'Comment by {self.commenter.username} on {self.post.title}'

class CommentReply(models.Model):
    comment = models.ForeignKey(Comment, on_delete=models.CASCADE, related_name='comment_replys')
    comment_replier =  models.ForeignKey(User, on_delete=models.CASCADE, related_name='repliers')   
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    def __str__(self):
      return f'Reply by {self.comment_replier.username} on {self.comment.body}'

blog/forms.py
from django import forms
from django.db.models import fields
from .models import Post, Comment, CommentReply

class PostForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = ['title', 'image', 'body', 'status', 'category', 'tags']

class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = ['body']

class CommentReplyForm(forms.ModelForm):

    class Meta:
        model = CommentReply
        fields = ['body']

blog/views.py
import json
from django.contrib.auth.decorators import login_required
from django.http.response import JsonResponse
from django.shortcuts import get_object_or_404, redirect, render
from .models import Post, Comment, Category, CommentReply
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.db.models import Count
from .forms import  CommentReplyForm, PostForm
from django.urls import reverse

# Create your views here.

def post_list_view(request, id=None):

    if id:
        category = Category.objects.get(id=id)
        posts = category.posts.all()

    else:
        posts =  Post.published.all()

    categories = Category.objects.all()
    paginator = Paginator(posts, 5)
    page = request.GET.get('page')

    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts  = paginator.page(paginator.num_pages)

    return render(request, 'posts_list.html', {'posts': posts, 'categories': categories})


def post_view(request, id):

    post = Post.objects.get(id=id)
    return render(request, 'post_view.html', {'post':post})

def post_detail(request, year, month, day, post):
    post = get_object_or_404(Post, slug=post, status='published', publish__year=year, publish__month=month, publish__day=day)
    comments = post.post_comments.filter(active=True)
    reply_form = CommentReplyForm()
    post_tags_ids = post.tags.values_list('id', flat=True)
    post_tags_names = post.tags.values_list('name', flat=True).all()
    print(post_tags_names.all())
    similar_posts = Post.published.filter(tags__in=post_tags_ids).exclude(id=post.id)
    similar_posts = similar_posts.annotate(same_tags=Count('tags')).order_by('-same_tags', '-publish')[:4]


    return render(request, 'post_view.html',{'post': post,
                                                     'comments': comments,
                                                     'reply_form': reply_form,
                                                     'similar_posts': similar_posts,
                                                     'tags': post_tags_names}
                                                     )
@login_required
def comment_api(request, year, month, day, post):
    post = get_object_or_404(Post, slug=post, status='published', publish__year=year, publish__month=month, publish__day=day)

    if request.body:
        print(request.body)
        data = json.loads(request.body.decode("utf-8"))
        body = data.get('body')
        Comment.objects.create(commenter=request.user, body=body, post=post)
        return JsonResponse({
            'message': "the comment submitted"
        })

@login_required
def like_btn(request, year, month, day, post,id):

    post = get_object_or_404(Post, slug=post, status='published', publish__year=year, publish__month=month, publish__day=day)

    if request.user not in post.likers.all():
        post.likers.add(request.user)
        return JsonResponse({
        'status': 'ok',
        "message": "like"
    })
    post.likers.remove(request.user)

    return JsonResponse({
        'status': 'ok',
        "message": "dislike"
    })

@login_required
def add_post(request):
    form = PostForm()
    if request.method == "POST":
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            post_form = form.save(commit=False)
            post_form.author = request.user
            post_form.save()
            form.save_m2m()
            return redirect(reverse("blogs:blogs_list"))

    context = {
        'form': form
    }
    return render(request, "add_post.html", context)

@login_required
def update_post(request, year, month, day, post):
    post = get_object_or_404(Post, slug=post, status='published', publish__year=year, publish__month=month, publish__day=day)
    form = PostForm(instance=post)
    if request.method == "POST":
        form = PostForm(request.POST, request.FILES, instance=post)
        if form.is_valid():
            post_form = form.save(commit=False)
            post_form.author = request.user
            post_form.save()
            form.save_m2m()
            return redirect(post.get_absolute_url())

    context = {
        'form': form
    }
    return render(request, "edit_post.html", context)

blog/templates/add_post.html
{% extends 'base.html' %}
{% load bootstrap4 %}


{% block body %}
<div class="bradcam_area bradcam_bg_1">
    <div class="container">
        <div class="row">
            <div class="col-xl-12">
                <div class="bradcam_text">
                    <h3>publish Your Post</h3>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="job_details_area">
        <div class="container">
            <div class="row">
                <div class="col-lg-8">
                    <div class="job_details_header">
                        <div class="single_jobs white-bg d-flex justify-content-between">


                        </div>
                    </div>
                    <div class="descript_wrap white-bg">
                        <div class="single_wrap">
                            <h4>Add A New Post</h4>
                        </div>

                    <div class="apply_job_form white-bg">

                                {# Display a form #}

                            <form method="post" class="form" enctype="multipart/form-data">

                                {% csrf_token %}
                                {{ form.media}}
                                {% bootstrap_form form %}
                                {% buttons %}

                                    <button class="boxed-btn3 w-100" type="submit">Submit</button>


                                {% endbuttons %}

                            </form>
                    </div>
                </div>

            </div>
        </div>
    </div>
    {% endblock %}

blog/templates/edit_post.html
{% extends 'base.html' %}
{% load bootstrap4 %}


{% block body %}
<div class="bradcam_area bradcam_bg_1">
    <div class="container">
        <div class="row">
            <div class="col-xl-12">
                <div class="bradcam_text">
                    <h3>Update Your Post</h3>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="job_details_area">
        <div class="container">
            <div class="row">
                <div class="col-lg-8">
                    <div class="job_details_header">
                        <div class="single_jobs white-bg d-flex justify-content-between">


                        </div>
                    </div>


                    <div class="apply_job_form white-bg">

                                {# Display a form #}

                            <form method="post" class="form" enctype="multipart/form-data">

                                {% csrf_token %}
                                {{ form.media}}
                                {% bootstrap_form form %}
                                {% buttons %}

                                    <button class="boxed-btn3 w-100" type="submit">Submit</button>


                                {% endbuttons %}

                            </form>
                    </div>
                </div>

            </div>
        </div>
    </div>
    {% endblock %}

blog/templates/posts_list.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% load blog_tags %}
{% load taggit_templatetags2_tags %}


{% block body %}
<!-- bradcam_area  -->
<div class="bradcam_area bradcam_bg_1">
    <div class="container">
        <div class="row">
            <div class="col-xl-12">
                <div class="bradcam_text">
                    <h3>blog</h3>
                </div>
            </div>
        </div>
    </div>
</div>
<!--/ bradcam_area  -->
<section class="blog_area section-padding">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 mb-5 mb-lg-0">
                <div class="blog_left_sidebar">
                    {% if posts %}


                        {% for post in posts %}
                        <article class="blog_item">
                            <div class="blog_item_img">
                                <img class="card-img rounded-0" src="{{post.image.url}}" alt="post_image" width="750px" height="365px">
                                <a href="#" class="blog_item_date">
                                    <h3>{{post.publish.day}}</h3>
                                    <p>{{ post.publish|date:'M' }}</p>
                                </a>
                            </div>

                            <div class="blog_details">
                                <a class="d-inline-block" href="{{post.get_absolute_url}}">
                                    <h2>{{post.title}}</h2>
                                </a>
                                <p>{{post.body|safe|truncatewords:50}}</p>
                                <ul class="blog-info-link">
                                    <li><a href="#"><i class="fa fa-user"></i>{% get_tags_for_object post as "tags" %} {%for tag in tags %} {{tag}}{%endfor%}</a></li>
                                    <li><a href="#"><i class="fa fa-comments"></i> {{post.post_comments.count}} Comments</a></li>
                                </ul>
                            </div>
                        </article>
                        {% endfor %}
                    {% else %}
                    <div class="alert alert-primary" role="alert">
                         Sorry, but there is no Posts for this category, yet!<a href="{%url 'home:index'%}" class="alert-link">Go Home Page</a>
                         <p> or be the first publisher  <a href="{% url 'blogs:add_post' %}" class="boxed-btn3">Add Post</a></p>
                      </div>
                    {% endif %}


                    {% if posts.has_other_pages %}

                    <nav class="blog-pagination justify-content-center d-flex">

                        <ul class="pagination">
                            <li class="page-item">
                                {% if posts.has_previous %}
                                <a href="?page={{ posts.previous_page_number }}" class="page-link" aria-label="Previous">
                                    <i class="ti-angle-left"></i>
                                </a>
                                {% endif %}
                            </li>
                            {% for i in posts.paginator.page_range %}
                            <li class="page-item">
                                <a href="?page={{i}}" class="page-link">{{i}}</a>
                            </li>
                            {% endfor %}

                            {% if posts.has_next %}
                            <li class="page-item">
                                <a href="?page={{ posts.next_page_number }}" class="page-link" aria-label="Next">
                                    <i class="ti-angle-right"></i>
                                </a>
                            </li>
                            {% endif %}
                        </ul>
                    </nav>
                    {% endif %}
                </div>
            </div>
            <div class="col-lg-4">
                <div class="blog_right_sidebar">
                    <aside class="single_sidebar_widget search_widget">
                        {% if posts %}
                        <a href="{% url 'blogs:add_post' %}" class="boxed-btn3" style="margin-bottom: 15px;">Add Post</a>
                        {% endif %}
                        <form action="#">
                            <div class="form-group">
                                <div class="input-group mb-3">
                                    <input type="text" class="form-control" placeholder='Search Keyword'
                                        onfocus="this.placeholder = ''"
                                        onblur="this.placeholder = 'Search Keyword'">
                                    <div class="input-group-append">
                                        <button class="btn" type="button"><i class="ti-search"></i></button>
                                    </div>
                                </div>
                            </div>
                            <button class="button rounded-0 primary-bg text-white w-100 btn_1 boxed-btn"
                                type="submit">Search</button>
                        </form>
                    </aside>

                    <aside class="single_sidebar_widget post_category_widget">
                        <h4 class="widget_title">Category</h4>
                        <ul class="list cat-list">

                            {% for category in categories %}
                            <li>
                                <a href="#" class="d-flex">
                                    <p>{{category.title}}</p>
                                    <p>({{category.posts.count}})</p>
                                </a>
                            </li>
                            {% endfor %}

                        </ul>
                    </aside>

                    <aside class="single_sidebar_widget popular_post_widget">
                        <h3 class="widget_title">Recent Post</h3>
                         {% show_recent_posts 5 %}

                    </aside>
                    <aside class="single_sidebar_widget tag_cloud_widget">
                        <h4 class="widget_title">Tag Clouds</h4>
                        <ul class="list">
                            {% get_taglist as tags for 'blog' %}
                            {%for tag in tags %}
                            <li>
                                <a href="#">{{tag}}</a>
                             </li>

                            {%endfor%}

                        </ul>
                    </aside>





                    <aside class="single_sidebar_widget newsletter_widget">
                        <h4 class="widget_title">Newsletter</h4>

                        <form action="#">
                            <div class="form-group">
                                <input type="email" class="form-control" onfocus="this.placeholder = ''"
                                    onblur="this.placeholder = 'Enter email'" placeholder='Enter email' required>
                            </div>
                            <button class="button rounded-0 primary-bg text-white w-100 btn_1 boxed-btn"
                                type="submit">Subscribe</button>
                        </form>
                    </aside>
                </div>
            </div>
        </div>
    </div>
</section>
<!--================Blog Area =================-->
{% endblock body %}

blog/templates/recent_posts.html
<!-- <ul>
    {% for post in recent_posts %}
    <li>
    <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
    </li>
    {% endfor %}
</ul> -->
{% load blog_tags %}

{% for post in recent_posts %}
<div class="media post_item">
    <img src="{{ post.image.url}}" alt="post" width="80px" height="80px">
    <div class="media-body">
        <a href="{{ post.get_absolute_url }}">
            <h3>{{post.title}}</h3>
        </a>
        <p>{{post.publish|time_ago}}</p>
    </div>
</div>
{% endfor %}