accounts/urls.py
from django.urls import path
from .views import candidate_profile, profile, edit_company_profile,edit_candidate_profile, sign_up_candidate, sign_up_company,company_profile

urlpatterns = [
    path('signup/candidate',sign_up_candidate , name = "sign_up_candidate"),
    path('signup/company',sign_up_company , name = "sign_up_company"),
    path('profile/', profile , name = "login_profile"),
    path('companies/profile/<int:id>',company_profile , name = "profile"),
    path('candidates/profile/<int:id>',candidate_profile , name = "candidate_profile"),
    path('companies/profile/<int:id>/edit', edit_company_profile, name = "profile_editor"),
    path('candidates/profile/<int:id>/edit', edit_candidate_profile, name = "candidate_profile_editor"),
]

app_name = 'accounts'

home/urls.py
from django.urls import path
from .views import candidates_view, companies_view, home_view
urlpatterns = [
    path('', home_view, name = "index"),
    path('candidates', candidates_view, name = "candidates"),
    path('companies', companies_view, name = "companies"),
    
]    

app_name = 'home'

job/urls.py
from django.urls import path
from .views import category_jobs, job_apply, job_details, jobs, add_job, like_btn

urlpatterns = [
    path('', jobs, name = "job_list"),
    path('<int:id>', job_details, name='job_details'),
    path('addJob', add_job, name='jobEditor'),
    path('<int:id>/like', like_btn, name='like'),
    path('<int:id>/apply', job_apply, name='application'),
    path('<int:id>', category_jobs, name='category_jobs'),
]

app_name = 'job'

project/urls.py
from django.contrib import admin
from django.urls import path, include 
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls', namespace='register')),
    path('admin/', admin.site.urls),   
    path('jobs/', include('job.urls', namespace='jobs')),
    path('contact-us/', include('contact.urls', namespace='contact')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('', include('home.urls', namespace="home")),
    path('blogs/', include('blog.urls', namespace='blogs')),
    

]

if settings.DEBUG:
    #urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/models.py
from django.db import models


# Create your models here.

home/views.py
from django.core.paginator import Paginator
from job.filters import JobFilter
from django.shortcuts import render
from job.models import Job, Category
from accounts.models import Employee, Company


# Create your views here.
def home_view(request):
    jobs = Job.objects.all()[:10]
    categories = Category.objects.all()
    candidaties = Employee.objects.all()
    companies = Company.objects.all()



    print(jobs)
    context = {
        "jobs": jobs,
        "categories": categories,
        "candidaties": candidaties,
        "companies": companies
    }
    return render(request, 'home.html', context)

def candidates_view(request):
    candidates = Employee.objects.all()
    paginator = Paginator(candidates, 8)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        "candidates": page_obj,
        }
    return render(request,"candidate.html",context)


def companies_view(request):
    companies = Company.objects.all()
    paginator = Paginator(companies, 8)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        "companies": page_obj,
        }
    return render(request,"companies.html",context)
# def category_jobs(request, id):
#     category = Category.objects.get(id=id)
#     jobs = category.jobs
#     my_filter = JobFilter(data=request.GET, queryset=jobs)
#     jobs_list = my_filter.qs

#     paginator = Paginator(jobs_list, 5)
#     page_number = request.GET.get('page')
#     page_obj = paginator.get_page(page_number)
#     context = {
#         "jobs_list": page_obj,
#         'my_filter': my_filter
#     }
#     return render(request, "job/job_list.html", context)

home/templates/candidate.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% load blog_tags %}
{% load taggit_templatetags2_tags %}

{% block body %}
  <!-- bradcam_area  -->
  <div class="bradcam_area bradcam_bg_1">
    <div class="container">
        <div class="row">
            <div class="col-xl-12">
                <div class="bradcam_text">
                    <h3>Candidates</h3>
                </div>
            </div>
        </div>
    </div>
</div>
<!--/ bradcam_area  -->

<!-- featured_candidates_area_start  -->
<div class="featured_candidates_area candidate_page_padding">
    <div class="container">
        <div class="row">
            {% for candidate in candidates  %}
            <div class="col-md-6 col-lg-3">
                <div class="single_candidates text-center">
                    <div class="thumb">
                        <img src="{{candidate.image.url}}" alt="">
                    </div>
                    <a href="{% url 'register:candidate_profile' candidate.user.id %}"><h4>{{candidate.user.get_full_name}}</h4></a>
                    <p>{{candidate.job_title}}</p>
                </div>
            </div>
            {% endfor %}

        </div>
        <div class="row">
             {% if candidates.has_other_pages %}

                            <div class="col-lg-12">
                                <div class="pagination_wrap">
                                    <ul>
                                        {% if candidates.has_previous %}
                                        <li><a href="?page={{candidates.previous_page_number}}"> <i class="ti-angle-left"></i> </a></li>
                                        {% endif %}
                                        {% for i in candidates.paginator.page_range %}
                                        <li><a href="?page={{i}}"><span>{{i}}</span></a></li>
                                        {% endfor %}
                                        {% if candidates.has_next %}
                                            <li><a href="?page={{candidates.next_page_number}}"> <i class="ti-angle-right"></i> </a></li>
                                        {% endif %}
                                    </ul>
                                </div>
                            </div>
                            {% endif %}
        </div>
    </div>
</div>
<!-- featured_candidates_area_end  -->
{% endblock body %}

home/templates/companies.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% load blog_tags %}
{% load taggit_templatetags2_tags %}

{% block body %}
  <!-- bradcam_area  -->
  <div class="bradcam_area bradcam_bg_1">
    <div class="container">
        <div class="row">
            <div class="col-xl-12">
                <div class="bradcam_text">
                    <h3>Companies</h3>
                </div>
            </div>
        </div>
    </div>
</div>
<!--/ bradcam_area  -->

<!-- featured_candidates_area_start  -->
<div class="featured_candidates_area candidate_page_padding">
    <div class="container">
        <div class="row">
            {% for company in companies  %}
            <div class="col-md-6 col-lg-3">
                <div class="single_candidates text-center">
                    <div class="thumb">
                        <img src="{{company.logo.url}}" alt="">
                    </div>
                    <a href="{% url 'register:profile' company.user.id %}"><h4>{{company.user.username}}</h4></a>
                    <p>{{company.category}}</p>
                </div>
            </div>
            {% endfor %}

        </div>
        <div class="row">
                 {% if companies.has_other_pages %}

                            <div class="col-lg-12">
                                <div class="pagination_wrap">
                                    <ul>
                                        {% if companies.has_previous %}
                                        <li><a href="?page={{companies.previous_page_number}}"> <i class="ti-angle-left"></i> </a></li>
                                        {% endif %}
                                        {% for i in companies.paginator.page_range %}
                                        <li><a href="?page={{i}}"><span>{{i}}</span></a></li>
                                        {% endfor %}
                                        {% if companies.has_next %}
                                            <li><a href="?page={{companies.next_page_number}}"> <i class="ti-angle-right"></i> </a></li>
                                        {% endif %}
                                    </ul>
                                </div>
                            </div>
                            {% endif %}
            </div>
        </div>
    </div>
</div>
<!-- featured_candidates_area_end  -->
{% endblock body %}