accounts/urls.py
from django.urls import path
from .views import candidate_profile, profile, edit_company_profile,edit_candidate_profile, sign_up_candidate, sign_up_company,company_profile

urlpatterns = [
    path('signup/candidate',sign_up_candidate , name = "sign_up_candidate"),
    path('signup/company',sign_up_company , name = "sign_up_company"),
    path('profile/', profile , name = "login_profile"),
    path('companies/profile/<int:id>',company_profile , name = "profile"),
    path('candidates/profile/<int:id>',candidate_profile , name = "candidate_profile"),
    path('companies/profile/<int:id>/edit', edit_company_profile, name = "profile_editor"),
    path('candidates/profile/<int:id>/edit', edit_candidate_profile, name = "candidate_profile_editor"),
]

app_name = 'accounts'

job/urls.py
from django.urls import path
from .views import category_jobs, job_apply, job_details, jobs, add_job, like_btn

urlpatterns = [
    path('', jobs, name = "job_list"),
    path('<int:id>', job_details, name='job_details'),
    path('addJob', add_job, name='jobEditor'),
    path('<int:id>/like', like_btn, name='like'),
    path('<int:id>/apply', job_apply, name='application'),
    path('<int:id>', category_jobs, name='category_jobs'),
]

app_name = 'job'

project/urls.py
from django.contrib import admin
from django.urls import path, include 
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls', namespace='register')),
    path('admin/', admin.site.urls),   
    path('jobs/', include('job.urls', namespace='jobs')),
    path('contact-us/', include('contact.urls', namespace='contact')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('', include('home.urls', namespace="home")),
    path('blogs/', include('blog.urls', namespace='blogs')),
    

]

if settings.DEBUG:
    #urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from ckeditor.fields import RichTextField
from django.conf import settings
from taggit.managers import TaggableManager
from job.models import Category, Job


# Create your models here.
def upload_company_image(instance, filename):
    extension = filename.split('.')[1]
    return 'companies/logos/%s.%s'%(instance.id, extension)

def upload_cv(instance, filename):
    extension = filename.split('.')[1]
    return 'candidaties/cvs/%s.%s'%(instance.id, extension)

def upload_image(instance, filename):
    extension = filename.split('.')[1]
    return 'candidaties/images/%s.%s'%(instance.id, extension)


class Profile(models.Model):
    user =  models.OneToOneField(User, on_delete=models.CASCADE, related_name='profile')
    phone = models.CharField(max_length = 15)
    city = models.ForeignKey("City", on_delete=models.CASCADE, null=True, related_name='user_profile')


@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)

class City(models.Model):
    name = models.CharField(max_length = 50)

    def __str__(self):
        return self.name

class Company(models.Model):
    logo = models.ImageField(upload_to=upload_company_image, null=True, blank=True)
    employee_num = models.IntegerField(default=0)
    description = RichTextField(blank=True, null=True)
    user =  models.OneToOneField(User, on_delete=models.CASCADE, related_name='company')
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True)

    def __str__(self):
        """Unicode representation of MODELNAME."""
        return self.user.username

class Employee(models.Model):
    job_title = models.CharField(max_length = 13)
    bio = models.TextField(max_length=500)
    user =  models.OneToOneField(User, on_delete=models.CASCADE, related_name='candidate')
    image = models.ImageField(upload_to=upload_image, null=True, blank=True)
    website = models.URLField(max_length = 300)
    cv = models.FileField(upload_to=upload_cv, null=True, blank=True)
    summary = RichTextField(blank=True, null=True)
    jobs = models.ManyToManyField(Job, related_name='candidaties', blank=True)
    objects = models.Manager()
    skills = TaggableManager()
    def __str__(self):
        return self.user.username

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms
from .models import Profile, Company, Employee 

class SignUpEmployeeForm(UserCreationForm):

    class Meta:
        model = User
        fields = ['username', 'email','first_name', 'last_name', 'password1', 'password2']

class SignUpCompanyForm(UserCreationForm):

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['city', 'phone']

class CompanyForm(forms.ModelForm):
    class Meta:
        model = Company
        fields = ['logo', 'employee_num', 'description', 'category']

class EmployeeForm(forms.ModelForm):
    class Meta:
        model = Employee
        fields = '__all__'
        exclude = ['user', 'jobs']
        

class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email']

class UserForm2(forms.ModelForm):
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email']

accounts/views.py
from django.http.response import HttpResponse
from django.shortcuts import render, redirect
from .forms import SignUpCompanyForm, SignUpEmployeeForm, ProfileForm, UserForm, CompanyForm, EmployeeForm
from django.contrib.auth import authenticate, login
from .models import Company, Profile, Employee
from django.contrib import messages
from django.urls import reverse
from django.contrib.auth.models import User


# Create your views here.
def sign_up_candidate(request):


    if request.method == "POST":
        form1 = SignUpEmployeeForm(request.POST)
        form2 = EmployeeForm(request.POST, request.FILES)
        if form1.is_valid() and form2.is_valid():
            print('valid')
            form1.save()
            username = form1.cleaned_data.get('username')
            password = form1.cleaned_data.get('password1')

            user = authenticate(username=username, password=password)
            if user:
                login(request, user)
                candidate_form = form2.save(commit=False)
                candidate_form.user = request.user
                candidate_form.save()
                form2.save_m2m()
                messages.success(request, 'Your have been successfully registered !')
                return redirect(reverse("register:candidate_profile", args=[user.id]))

            else:

                return HttpResponse('there something wrong !')
    else:
        form1 = SignUpEmployeeForm()
        form2 = EmployeeForm()

    context = {
        'form1': form1,
        "form2":form2
    }

    return render(request, 'registration/signup.html', context)

def sign_up_company(request):

    if request.method == "POST":

        form1 = SignUpCompanyForm(request.POST)
        form2 = CompanyForm(request.POST, request.FILES)
        if form1.is_valid() and form2.is_valid():
            form1.save()
            username = form1.cleaned_data.get('username')
            password = form1.cleaned_data.get('password1')
            user = authenticate(username=username, password=password)
            if user:
                    login(request, user)
                    company_form = form2.save(commit=False)
                    company_form.user = request.user
                    company_form.save()
                    messages.success(request, 'Your have been successfully registered !')
                    return redirect(reverse('register:profile', args=[user.id]))

            else:

                    return HttpResponse('there something wrong !')
    else:
        form1 = SignUpCompanyForm()
        form2 = CompanyForm()

    context = {
        'form1': form1,
        "form2": form2
    }

    return render(request, 'registration/signup.html', context)
def profile(request):
    user = request.user
    try:
        if user.candidate != None :
            return redirect(reverse("register:candidate_profile", args=[user.id]))
    except:
        return redirect(reverse("register:profile", args=[user.id]))

    #elif user.company != None:
       # return redirect(reverse("register:profile", args=[user.id]))
    #else:
        #return redirect(reverse("home:index"))

def company_profile(request, id):

    user = User.objects.get(id=id)
    profile = Profile.objects.get(user=user)
    return render(request, 'accounts/profile.html', {'profile': profile})

def candidate_profile(request, id):
    user = User.objects.get(id=id)
    profile = Profile.objects.get(user=user)
    return render(request, 'accounts/candidate_profile.html', {'profile': profile})



def edit_company_profile(request, id):

    profile = Profile.objects.get(user=request.user)
    company = Company.objects.get(user=request.user)
    if request.method == "POST":
        profileform = ProfileForm(request.POST,request.FILES, instance=profile)
        userform = UserForm(request.POST, instance=request.user )
        companyform = CompanyForm(request.POST,request.FILES, instance=company)
        if profileform.is_valid() and userform.is_valid():
            userform.save()
            my_profileform = profileform.save(commit=False)
            my_profileform.user = request.user
            my_profileform.save()
            my_companyform = companyform.save(commit=False)
            my_companyform.user = request.user
            my_companyform.save()
            return redirect(reverse('register:profile', args=[request.user.id]))
    else:
        profileform = ProfileForm(instance=profile)
        userform = UserForm(instance=request.user)
        companyform = CompanyForm(instance=company)

    context = {
        'profileform': profileform,
        'userform': userform,
        'companyform': companyform
    }
    return render(request, 'accounts/profile_edit.html', context)

def edit_candidate_profile(request, id):

    profile = Profile.objects.get(user=request.user)
    candidate = Employee.objects.get(user=request.user)
    if request.method == "POST":
        profileform = ProfileForm(request.POST,request.FILES, instance=profile)
        userform = UserForm(request.POST, instance=request.user )
        candidateform = EmployeeForm(request.POST,request.FILES, instance=candidate)
        if profileform.is_valid() and userform.is_valid():
            userform.save()
            my_profileform = profileform.save(commit=False)
            my_profileform.user = request.user
            my_profileform.save()
            my_candidateform = candidateform.save(commit=False)
            my_candidateform.user = request.user
            my_candidateform.save()
            return redirect(reverse('register:candidate_profile', args=[request.user.id]))
    else:
        profileform = ProfileForm(instance=profile)
        userform = UserForm(instance=request.user)
        candidateform = EmployeeForm(instance=candidate)

    context = {
        'profileform': profileform,
        'userform': userform,
        'candidateform': candidateform
    }
    return render(request, 'accounts/candidate_profile_edit.html', context)

accounts/templates/accounts/candidate_profile.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% load blog_tags %}
{% load taggit_templatetags2_tags %}

{% block head %}
<meta charset="utf-8">
<!--  This file has been downloaded from bootdey.com    @bootdey on twitter -->
<!--  All snippets are MIT license http://bootdey.com/license -->
<title>profile with data and skills - Bootdey.com</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<link href="http://netdna.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" rel="stylesheet">

{% endblock head %}

{% block style %}
   <style type="text/css">
    body{
margin-top:20px;
color: #1a202c;
text-align: left;
background-color: #e2e8f0;
}
.main-body {
padding: 15px;
}
.card {
box-shadow: 0 1px 3px 0 rgba(0,0,0,.1), 0 1px 2px 0 rgba(0,0,0,.06);
}

.card {
position: relative;
display: flex;
flex-direction: column;
min-width: 0;
word-wrap: break-word;
background-color: #fff;
background-clip: border-box;
border: 0 solid rgba(0,0,0,.125);
border-radius: .25rem;
}

.card-body {
flex: 1 1 auto;
min-height: 1px;
padding: 1rem;
}

.gutters-sm {
margin-right: -8px;
margin-left: -8px;
}

.gutters-sm>.col, .gutters-sm>[class*=col-] {
padding-right: 8px;
padding-left: 8px;
}
.mb-3, .my-3 {
margin-bottom: 1rem!important;
}

.bg-gray-300 {
background-color: #e2e8f0;
}
.h-100 {
height: 100%!important;
}
.shadow-none {
box-shadow: none!important;
}

</style>
   {% endblock style %}

   {% block body %}
   <!-- bradcam_area  -->
  <div class="bradcam_area bradcam_bg_1">
    <div class="container">
        <div class="row">
            <div class="col-xl-12">
                <div class="bradcam_text">
                    <h3>{{profile.user.username}}</h3>
                </div>
            </div>
        </div>
    </div>
</div>
<!--/ bradcam_area  -->


<div class="container">
    <div class="main-body">


          <div class="row gutters-sm">
            <div class="col-md-4 mb-3">
              <div class="card">
                <div class="card-body">
                  <div class="d-flex flex-column align-items-center text-center">
                    <img src="{{profile.user.candidate.image.url}}" alt="Admin" class="rounded-circle" width="150">
                    <div class="mt-3">
                      <h4>{{profile.user.get_full_name}}</h4>
                      <p class="text-secondary mb-1">{{profile.user.candidate.job_title}}</p>
                      <p class="text-muted font-size-sm">{{profile.city}}</p>

                      <button class="btn btn-outline-primary">
                          <a class="boxed-btn3 w-100" href="{% url 'register:candidate_profile_editor' profile.user.id %}">Edit <i class="bi bi-pencil-fill"></i></a>

                          </button>

                    </div>
                  </div>
                </div>
              </div>
              <div class="card mt-3">
                <ul class="list-group list-group-flush">
                  <li class="list-group-item d-flex justify-content-between align-items-center flex-wrap">
                    <h6 class="mb-0"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-globe mr-2 icon-inline"><circle cx="12" cy="12" r="10"></circle><line x1="2" y1="12" x2="22" y2="12"></line><path d="M12 2a15.3 15.3 0 0 1 4 10 15.3 15.3 0 0 1-4 10 15.3 15.3 0 0 1-4-10 15.3 15.3 0 0 1 4-10z"></path></svg>Website</h6>
                    <a href="{{profile.user.candidate.website}}"><span class="text-secondary">My Website</span></a>
                  </li>

                </ul>
              </div>
            </div>
            <div class="col-md-8">
              <div class="card mb-3">
                <div class="card-body">
                  <div class="row">
                    <div class="col-sm-3">
                      <h6 class="mb-0">Full Name</h6>
                    </div>
                    <div class="col-sm-9 text-secondary">
                        {{profile.user.get_full_name}}
                    </div>
                  </div>
                  <hr>
                  <div class="row">
                    <div class="col-sm-3">
                      <h6 class="mb-0">Email</h6>
                    </div>
                    <div class="col-sm-9 text-secondary">
                      {{profile.user.email}}
                    </div>
                  </div>
                  <hr>
                  <div class="row">
                    <div class="col-sm-3">
                      <h6 class="mb-0">Phone</h6>
                    </div>
                    <div class="col-sm-9 text-secondary">
                        {{profile.phone}}
                    </div>
                  </div>
                  <hr>
                  <div class="row">
                    <div class="col-sm-3">
                      <h6 class="mb-0">Mobile</h6>
                    </div>
                    <div class="col-sm-9 text-secondary">
                        {{profile.phone}}
                    </div>
                  </div>
                  <hr>
                  <div class="row">
                    <div class="col-sm-3">
                      <h6 class="mb-0">Address</h6>
                    </div>
                    <div class="col-sm-9 text-secondary">
                        {{profile.city}}
                    </div>
                  </div>
                </div>
              </div>
              <div class="row gutters-sm">
                <div class="col-sm-6 mb-3">
                  <div class="card h-100">
                    <div class="card-body">
                      <h6 class="d-flex align-items-center mb-3"><i class="material-icons text-info mr-2">assignment</i>Project Status</h6>
                      {% get_tags_for_object profile.user.candidate as "tags" %} \
                      {%for tag in tags %}

                      <small>{{tag}}</small>
                      <div class="progress mb-3" style="height: 5px">
                        <div class="progress-bar bg-primary" role="progressbar" style="width: 80%" aria-valuenow="80" aria-valuemin="0" aria-valuemax="100"></div>
                      </div>
                      {%endfor%}


                    </div>
                  </div>
                </div>
                <div class="col-sm-6 mb-3">
                  <div class="card h-100">
                    <div class="card-body">
                      <h6 class="d-flex align-items-center mb-3"><i class="material-icons text-info mr-2">assignment</i>Project Status</h6>
                      <small>Web Design</small>
                      <div class="progress mb-3" style="height: 5px">
                        <div class="progress-bar bg-primary" role="progressbar" style="width: 80%" aria-valuenow="80" aria-valuemin="0" aria-valuemax="100"></div>
                      </div>
                      <small>Website Markup</small>
                      <div class="progress mb-3" style="height: 5px">
                        <div class="progress-bar bg-primary" role="progressbar" style="width: 72%" aria-valuenow="72" aria-valuemin="0" aria-valuemax="100"></div>
                      </div>
                      <small>One Page</small>
                      <div class="progress mb-3" style="height: 5px">
                        <div class="progress-bar bg-primary" role="progressbar" style="width: 89%" aria-valuenow="89" aria-valuemin="0" aria-valuemax="100"></div>
                      </div>
                      <small>Mobile Template</small>
                      <div class="progress mb-3" style="height: 5px">
                        <div class="progress-bar bg-primary" role="progressbar" style="width: 55%" aria-valuenow="55" aria-valuemin="0" aria-valuemax="100"></div>
                      </div>
                      <small>Backend API</small>
                      <div class="progress mb-3" style="height: 5px">
                        <div class="progress-bar bg-primary" role="progressbar" style="width: 66%" aria-valuenow="66" aria-valuemin="0" aria-valuemax="100"></div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
    </div>
<script src="http://code.jquery.com/jquery-1.10.2.min.js"></script>
<script src="http://netdna.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
<script type="text/javascript">

</script>
{% endblock body %}

accounts/templates/accounts/candidate_profile_edit.html
{% extends 'base.html' %}
{% load bootstrap4 %}
<body>
    <!--[if lte IE 9]>
            <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="https://browsehappy.com/">upgrade your browser</a> to improve your experience and security.</p>
        <![endif]-->

    <!-- header-start -->
    {% block body %}
    <!-- header-end -->


    <!--/ bradcam_area  -->

    <div class="job_details_area">
        <div class="container">
            <div class="row">
                <div class="col-lg-8">
                    <div class="job_details_header">
                        <div class="single_jobs white-bg d-flex justify-content-between">


                        </div>
                    </div>
                    <div class="descript_wrap white-bg">
                        <div class="single_wrap">
                            <h4>Edit Profile</h4>
                        </div>

                    <div class="apply_job_form white-bg">

                                {# Display a form #}

                            <form method="post" class="form" enctype="multipart/form-data">

                                {% csrf_token %}
                                {% bootstrap_form userform %}
                                {% bootstrap_form profileform %}
                                {{candidateform.media}}
                                {% bootstrap_form candidateform %}
                                {% buttons %}

                                        <button class="boxed-btn3 w-100" type="submit">Submit</button>


                                {% endbuttons %}
                            </div>
                            </form>
                    </div>
                </div>

            </div>
        </div>
    </div>
    {% endblock %}
    <!-- footer start -->

</body>

</html>

accounts/templates/accounts/profile.html
{% extends 'base.html' %}
{% load bootstrap4 %}
<body>
    <!--[if lte IE 9]>
            <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="https://browsehappy.com/">upgrade your browser</a> to improve your experience and security.</p>
        <![endif]-->
    {% block body %}
    <!-- header-start -->

    <!-- bradcam_area  -->
    <div class="bradcam_area bradcam_bg_1">
        <div class="container">
            {% if messages %}
                <ul class="messages">
                    {% for message in messages %}
                    <div class="alert alert-success" role="alert">
                        {{ message }}
                    </div>

                    {% endfor %}
                </ul>
            {% endif %}
            <div class="row">
                <div class="col-xl-12">
                    <div class="bradcam_text">
                        <h3>{{profile.user.username|title}}</h3>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!--/ bradcam_area  -->

    <div class="job_details_area">
        <div class="container">
            <div class="row">
                 <div class="col-md-6 col-lg-3">
                <div class="single_candidates text-center">
                    <div class="thumb">
                        <img src="{{profile.user.company.logo.url}}" alt="">
                    </div>
                    <div class="p-6">
                            <a class="boxed-btn3 w-100" href="{% url 'register:profile_editor' profile.user.id %}">Edit <i class="bi bi-pencil-fill"></i></a>
                    </div>
                </div>
            </div>
                <div class="col-lg-8 mx-auto">
                    <div class="job_sumary">
                        <div class="summery_header">

                            <h3>General Info</h3>
                        </div>
                        <div class="job_content">
                            <ul>
                                <li>Name: <span>{{profile.user.username|title}}</span></li>
                                <li>About us: <span>{{profile.user.company.description|safe}}</span></li>
                                <li>Employee number: <span>{{profile.user.company.employee_num}}</span></li>
                                <li>Our Caregory: <span>{{profile.user.company.category}}</span></li>

                            </ul>
                        </div>

                    </div>

                    <div class="job_sumary">
                        <div class="summery_header">

                            <h3>Contact Info</h3>
                        </div>
                        <div class="job_content">
                            <ul>

                                <li>Phone: <span>{{profile.phone}}</span></li>
                                <li>Email: <span>{{profile.user.email}}</span></li>
                                <li>Location: <span>{{profile.city.name}}</span></li>

                            </ul>
                        </div>

                    </div>


                </div>
            </div>
        </div>
    </div>
    {% endblock %}
    <!-- footer start -->

</body>

</html>

accounts/templates/accounts/profile_edit.html
{% extends 'base.html' %}
{% load bootstrap4 %}
<body>
    <!--[if lte IE 9]>
            <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="https://browsehappy.com/">upgrade your browser</a> to improve your experience and security.</p>
        <![endif]-->

    <!-- header-start -->
    {% block body %}
    <!-- header-end -->


    <!--/ bradcam_area  -->

    <div class="job_details_area">
        <div class="container">
            <div class="row">
                <div class="col-lg-8">
                    <div class="job_details_header">
                        <div class="single_jobs white-bg d-flex justify-content-between">


                        </div>
                    </div>
                    <div class="descript_wrap white-bg">
                        <div class="single_wrap">
                            <h4>Edit Profile</h4>
                        </div>

                    <div class="apply_job_form white-bg">

                                {# Display a form #}

                            <form method="post" class="form" enctype="multipart/form-data">

                                {% csrf_token %}
                                {% bootstrap_form userform %}
                                {% bootstrap_form profileform %}
                                {{companyform.media}}
                                {% bootstrap_form companyform %}
                                {% buttons %}

                                        <button class="boxed-btn3 w-100" type="submit">Submit</button>


                                {% endbuttons %}
                            </div>
                            </form>
                    </div>
                </div>

            </div>
        </div>
    </div>
    {% endblock %}
    <!-- footer start -->

</body>

</html>